config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'se_connecter' => 'sessions#new', as: :se_connecter
  get 'se_deconnecter' => 'sessions#destroy', as: :se_deconnecter
  get 'inscription' => 'user#new', as: :inscription

  get 'profil' => 'user#show', as: :profil

  resources :actualites
  resources :musees
  resources :sessions
  resources :user
end

app/models/actualite.rb
class Actualite < ActiveRecord::Base
  attr_accessor :name, :title, :uniteam_id, :content, :date, :image_url

  def initialize(attributes)
    self.name = attributes[:name]
    self.title = attributes[:title]
    self.uniteam_id = attributes[:uniteam_id]
    self.content = attributes[:content]
    self.date = attributes[:date]
    self.image_url = attributes[:image_url]
  end

  def self.recent(count = 3)
    actualites = UniteamAPI::Actualite.recent(count)
    total_count  = actualites[:total_count]
    items = actualites[:items].collect do |actualite|
      new actualite
    end
    { :items => items, :total_count => total_count }
  end

  def self.list(count = 10, offset = 0)
    actualites = UniteamAPI::Actualite.list(count, offset)
    total_count  = actualites[:total_count]
    offset = actualites[:offset]
    count = actualites[:count]
    items = actualites[:items].collect do |actualite|
      new actualite
    end
    { :items => items, :total_count => total_count, :offset => offset, :count => count }
  end

  def self.find(id)
    actualite = UniteamAPI::Actualite.find(id)
    new actualite
  end
  
end

app/controllers/actualites_controller.rb
class ActualitesController < ApplicationController

  before_action :set_actualite, only: [:show, :edit, :update, :destroy]

  def index
    page = params[:page].to_i
    per_page = 10
    offset = page * per_page
    @list_actualites = Actualite.list(per_page, offset)
    @pagination = Kaminari.paginate_array(
      @list_actualites[:items],
      total_count: @list_actualites[:total_count]
      ).page(params[:page]).per(per_page)
  end

  def show
  end

  private
    def set_actualite
      @actualite = Actualite.find(params[:id])
    end

    def actualite_params
      params.require(:actualite).permit(:title, :name, :uniteam_id, :content, :date, :image_url)
    end
end

app/helpers/actualites_helper.rb
module ActualitesHelper
end

app/views/actualites/index.html.erb
<h1>Actualites</h1>

<p class="total-count"><%= @list_actualites[:total_count] %> <%= "item".pluralize(@list_actualites[:total_count]) %></p>

<ul class="actualites-list">
  <% @list_actualites[:items].each do |actualite| %>
    <li class="actualites-list-item">
      <%= link_to(actualite_path(actualite.uniteam_id)) do %>
      <%= image_tag api_image(actualite.image_url, "news") %>
        <%= content_tag(:h5, actualite.name) %>
        <%= content_tag(:h6, (l Time.at(actualite.date))) %>
      <% end %>

  <% end %>
</ul>

<%= paginate @pagination %>

  

app/views/actualites/show.html.erb
<h1><%= @actualite.name %></h1>
<h2><%= @actualite.title %></h2>
<div class="content"><%= sanitize @actualite.content.html_safe %></div>