config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'se_connecter' => 'sessions#new', as: :se_connecter
  get 'se_deconnecter' => 'sessions#destroy', as: :se_deconnecter
  get 'inscription' => 'user#new', as: :inscription

  get 'profil' => 'user#show', as: :profil

  resources :actualites
  resources :musees
  resources :sessions
  resources :user
end

app/models/musee.rb
class Musee < ActiveRecord::Base
  attr_accessor :name, :title, :uniteam_id, :summary, :image_url, :latitude, :longtitude, :address, :city, :country, :zip_code, :video, :ticketnet_url, :wikipedia_url, :opening_hours, :cost, :rating

  def initialize(attributes)
    self.name = attributes[:name]
    self.title = attributes[:title]
    self.uniteam_id = attributes[:uniteam_id]
    self.summary = attributes[:summary]
    self.image_url = attributes[:image_url]
    self.latitude = attributes[:latitude]
    self.longtitude = attributes[:longtitude]
    self.address = attributes[:address]
    self.city = attributes[:city]
    self.country = "France"
    self.zip_code = attributes[:zip_code]
    self.video = attributes[:video]
    self.ticketnet_url = attributes[:ticketnet_url]
    self.wikipedia_url = attributes[:wikipedia_url]
    self.opening_hours = attributes[:opening_hours]
    self.cost = attributes[:cost]
    self.rating = attributes[:rating]
  end

  def self.recent(count = 3)
    musees = UniteamAPI::Musee.recent(count)
    total_count  = musees[:total_count]
    items = musees[:items].collect do |musee|
      new musee
    end
    { :items => items, :total_count => total_count }
  end

  def self.list(count = 10, offset = 0)
    musees = UniteamAPI::Musee.list(count, offset)
    total_count  = musees[:total_count]
    offset = musees[:offset]
    count = musees[:count]
    items = musees[:items].collect do |musee|
      new musee
    end
    { :items => items, :total_count => total_count, :offset => offset, :count => count }
  end

  def self.find(id)
    musee = UniteamAPI::Musee.find(id)
    new musee
  end
  
end

app/controllers/musees_controller.rb
class MuseesController < ApplicationController
  before_action :set_musee, only: [:show, :edit, :update, :destroy]

  def index
    page = params[:page].to_i
    per_page = 10
    offset = page * per_page
    @list_musees = Musee.list(per_page, offset)
    @pagination = Kaminari.paginate_array(
      @list_musees[:items],
      total_count: @list_musees[:total_count]
      ).page(params[:page]).per(per_page)
  end

  def show
  end

  private
    def set_musee
      @musee = Musee.find(params[:id])
    end
end

app/helpers/musees_helper.rb
module MuseesHelper
end

app/views/musees/index.html.erb
<h1>Musees</h1>

<p class="total-count"><%= @list_musees[:total_count] %> <%= "item".pluralize(@list_musees[:total_count]) %></p>

<ul class="musees-list">
  <% @list_musees[:items].each do |musee| %>
    <li class="musees-list-item">
      <%= link_to(musee_path(musee.uniteam_id)) do %>
        <%= image_tag api_image(musee.image_url, "museum") %>
        <%= content_tag(:h5, musee.name) %>
        <%= content_tag(:h6, musee.summary) %>
        <%= content_tag(:p, "#{musee.city}, #{musee.country}") %>
      <% end %>
  <% end %>
</ul>

<%= paginate @pagination %>

app/views/musees/show.html.erb
<h1><%= @musee.name %></h1>
<h2><%= @musee.title %></h2>
<div class="content"><%= sanitize @musee.summary.html_safe %></div>